# Generated by Django 5.2.1 on 2025-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_subtaskcompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtaskcompletion",
            name="completed",
            field=models.BooleanField(default=True),
        ),
    ]
