# Generated by Django 5.2.1 on 2025-05-24 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_subtaskcompletion_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtaskcompletion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
