# Generated by Django 5.2.1 on 2025-05-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_subtaskcompletion_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
